services:
  php:
    build:
      context: ./php
    container_name: php-container
    volumes:
      - ./www:/var/www/html
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
